[package]
name = "vtable_util"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
darling = "0.20"
itertools = "0.13"
regex = "1.10"
syn = "2.0"
walkdir = "2.5"